language: node_js
addons:
    apt:
        packages:
            - language-pack-fr
env:
    global:
        - LANG=fr_FR.UTF-8
        - LC_ALL=fr_FR.UTF-8
node_js:
    - "node"
    - "6"

install:
    - npm install

script:
    - npm run test
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
