language: node_js
sudo: true
node_js:
  - "node"

install:
  - npm install

script:
  - npm run test:unit
  - npm run lint

after_success:
  - npm install coveralls
  - coveralls < coverage/lcov.info
