language: node_js
sudo: true
node_js:
  - "node"

install:
  - npm install

script:
  - npm run test:unit

jobs:
  include:
    - name: "Lint"
      script: npm run lint

after_success:
  - npm run coveralls
